### ISSUE TITLE
property 'browser.supportsWebRtc'

### ISSUE THREAD

**Issue by dimitrivdp** [willviles/ember-useragent#10]
Hi,

Would it be useful to have a property:

`userAgent.get('browser. browser.supportsWebRtc'); // Boolean`

Or do you want it to keept it close to the browser properties and not make conclusions that may have to be maintained?

What do you think?

KR,

Dimitri.

**Comment by willviles** [comment]
Hi Dimitri - thanks for the suggestion! 

I'd quite like to steer clear of trying to infer browser features and keep this addon simply for reliably parsing the UA.

However, perhaps you could create a new addon which offers feature detection via a `browserFeatures` service? For feature detection in FastBoot, it could leverage Ember UserAgent to best-guess feature support based on browser version.
