### ISSUE TITLE
Headless Chrome for Acceptance Tests

### ISSUE THREAD

**Issue by jleja** [willviles/ember-useragent#11]
Any thoughts on either including Headless Chrome in the `isChrome` or some other related property?  Was wondering why my acceptance tests failed after updating to the latest version of this component, and it turned out that Headless Chrome !== Chrome.  For now, just checking the browser info.name for "Headless Chrome", but might be nice to capture it somehow .

**Comment by willviles** [comment]
@jleja `browser.isChromeHeadless` is added to the UserAgent service in the new release [0.5.0](https://github.com/willviles/ember-useragent/releases/tag/0.5.0). 

Thanks for the suggestion! 👍
