### ISSUE TITLE
isLinux in Firefox 59.0 false for Ubuntu

### ISSUE THREAD

**Issue by paulgoetze** [willviles/ember-useragent#15]
It seems like (at least the latest v59.0) Firefox does not return `Linux` as the os (On Ubuntu I get `Ubuntu` instead of `Linux`). 

Chrome, however, returns `Linux` for me on Ubuntu as well, so here it works.

So, the `userAgent.os.isLinux` property returns false where it should be true.

**Comment by willviles** [comment]
Hi Paul! Could you post an issue on [ua-parser-js](https://github.com/faisalman/ua-parser-js) for this problem?

In the mean time, you might like to try `yarn upgrade ua-parser-js` unless you're not getting the latest (`0.7.17`), where there may be a fix!

**Comment by paulgoetze** [comment]
Ah, yes, sorry @willviles, I didn’t get that the service just uses the ua-parser functions. Will do.
(My ua-parser-js is already v0.7.17, though). Thanks for the fast reply!

**Comment by paulgoetze** [comment]
On the other hand, if I read the [ua-parser-js docs](https://github.com/faisalman/ua-parser-js#methods) correctly, they just provide different Linux distributions (Ubuntu amongst them) as `os.name`. Similar to what is done [in the service](https://github.com/willviles/ember-useragent/blob/master/addon/services/user-agent.js#L89-L91) for `isWindows`. So should ember-useragent check for all Linux Distributions as well?

**Comment by willviles** [comment]
@paulgoetze - good spot! I've released `0.6.0` which [checks for popular Linux distributions](https://github.com/willviles/ember-useragent/blob/0.6.0/addon/services/user-agent.js#L87-L90) and sets the `isLinux` quick-access property accordingly!

**Comment by paulgoetze** [comment]
Awesome, thanks @willviles! :rocket:
