### ISSUE TITLE
Updating from 0.6.1 to 0.7.1 causes the build to fail

### ISSUE THREAD

**Issue by lpaulger** [willviles/ember-useragent#24]
After updating from `0.6.1` to `07.1` I'm encountering the following error:

```while import node_modules/ua-parser-js/src/ua-parser.js: found an unknown transformation name cjs. Available transformNames are: amd```

stack trace and error report:
```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: while import node_modules/ua-parser-js/src/ua-parser.js: found an unknown transformation name cjs. Available transformNames are: amd
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: while import node_modules/ua-parser-js/src/ua-parser.js: found an unknown transformation name cjs. Available transformNames are: amd
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: while import node_modules/ua-parser-js/src/ua-parser.js: found an unknown transformation name cjs. Available transformNames are: amd
    at options.using.forEach.entry (/Users/lpaulger/Documents/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:1801:19)
    at Array.forEach (<anonymous>)
    at EmberApp._import (/Users/lpaulger/Documents/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:1792:23)
    at EmberApp.import (/Users/lpaulger/Documents/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:1765:10)
    at Class.included (/Users/lpaulger/Documents/myApp/node_modules/ember-useragent/index.js:9:15)
    at Class.superWrapper [as included] (/Users/lpaulger/Documents/myApp/node_modules/core-object/lib/assign-properties.js:34:20)
    at project.addons.forEach.addon (/Users/lpaulger/Documents/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:596:15)
    at Array.forEach (<anonymous>)
    at EmberApp._notifyAddonIncluded (/Users/lpaulger/Documents/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:594:25)
    at new EmberApp (/Users/lpaulger/Documents/myApp/node_modules/ember-cli/lib/broccoli/ember-app.js:151:10)
```

**Comment by richard-viney** [comment]
What platform are you on?

**Comment by buschtoens** [comment]
This is probably a case of: https://github.com/rwjblue/ember-cli-cjs-transform/issues/22

The solution above isn't ideal, since it probably generates these warnings in host apps that already have `ember-cli-cjs-transform` themselves as a dependency, but it appears to be a valid fix.

**Comment by lpaulger** [comment]
@buschtoens is there anything I can do to bypass this warning? the reference to rwjblue/ember-cli-cjs-transform#22 seems to reference a chance required to this addon, or are you suggesting a PR request?

**Comment by buschtoens** [comment]
Yes, by submitting this line as a PR to ember-useragent:

```js
importTransforms: require('ember-cli-cjs-transform').importTransforms
```

We could fix the crash for host apps that don't have ember-cli-cjs-transform installed.

However, that would cause this (apparently harmless) warning:

> WARNING: Addon "ember-cli-cjs-transform" is defining a transform name: cjs that is already being defined. Using transform from addon: "ember-cli-cjs-transform".

The alternative is to

- instruct users of ember-useragent to install ember-cli-cjs-transform
- automatically install ember-cli-cjs-transform during the installation of ember-useragent

tbh I'm just eagerly awaiting https://github.com/ef4/ember-auto-import/issues/119 so that we can use it instead of the CJS transform.

**Comment by willviles** [comment]
> - automatically install ember-cli-cjs-transform during the installation of ember-useragent

I could implement this as a stop gap until https://github.com/ef4/ember-auto-import/issues/119 drops?

**Comment by willviles** [comment]
@lpaulger Correct. Ember UserAgent currently depends upon `ember-cli-cjs-transform` being installed in your project. I'm hoping there's a happy path forward with `ember-auto-import` very soon. I'll look into it ASAP, but in the meantime PRs are welcomed!

**Comment by willviles** [comment]
I've created a [branch](https://github.com/willviles/ember-useragent/tree/feat/ember-auto-import) for implementing `ember-auto-import`. Try it out:

```npm i -S git://github.com/willviles/ember-useragent.git#ember-auto-import ```
