### ISSUE TITLE
Template helper proposal

### ISSUE THREAD

**Issue by bobisjan** [willviles/ember-useragent#25]
Hi 👋,

based on the upcoming addition of `media` helper into `ember-responsive` add-on https://github.com/freshbooks/ember-responsive#getting-started, I propose adding similar helper here like this

```hbs
{{#if (user-agent "browser.isChrome")}}
  Chrome, here...
{{/if}}
```

What do you think? I'm happy to send a pull request.

**Comment by willviles** [comment]
@bobisjan - it'd definitely be good to have quick access to all the [service props](https://github.com/willviles/ember-useragent#service-properties) via a template helper.

The only change to your proposal is that we'll need to prepend each property type to the getter argument. For example:

```hbs
{{#if (user-agent 'browser.isChrome')}}
```

```hbs
{{#if (user-agent 'os.isAndroid')}}
```

More than happy to merge in a PR from you!
