### ISSUE TITLE
Fastboot deprecation

### ISSUE THREAD

**Issue by oskarrough** [willviles/ember-useragent#4]
Hi, seeing this with ember-cli-fastboot 1.0.0 rc.2.

```bash
DEPRECATION: Having fastboot specific code in app directory of 
/Users/xxx/Sites/xxx/node_modules/ember-useragent is deprecated. Please move it to fastboot/app directory.
```

I think it is this https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c#addon-containing-fastboot-based-initializers-as-appinstance-initializersfastbootjs

Also see https://github.com/ember-fastboot/ember-cli-fastboot/issues/387#issuecomment-304445510

**Comment by willviles** [comment]
Thanks @oskarrough. I'll get a PR for this merged in tonight!
